<?xml version="1.0"?>
<robot name="k3robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Imports -->
    <xacro:include filename="colors.xacro"/>
    <xacro:include filename="robot_constants.xacro"/>
    <xacro:include filename="inertial_properties.xacro"/>
    <xacro:include filename="lidar.xacro"/>
    <xacro:include filename="gazebo_control.xacro"/>
    <xacro:include filename="camera.xacro"/>

    
    <!-- Robot Footprint -->
    <link name="base_footprint"/>

    <!-- Robot Base -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="2.8" w="${base_width}" d="${base_length}" h="${base_height}"/>
    </link>

    <gazebo reference="base_link">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 ${-(wheel_radius + wheel_zoff)}" rpy="0 0 0"/>
    </joint>

      <!-- Robot Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect xoffset">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.2" r="${wheel_radius}" h="${wheel_width}"/>
      
    </link>

    <gazebo reference="${prefix}_link">
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff + xoffset} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

    <xacro:wheel prefix="drivewhl_lf" x_reflect="-1" y_reflect="1" xoffset="0.14"/>
    <xacro:wheel prefix="drivewhl_rf" x_reflect="-1" y_reflect="-1" xoffset="0.14"/>

    <xacro:wheel prefix="drivewhl_lm" x_reflect="-1" y_reflect="1" xoffset="0"/>
    <xacro:wheel prefix="drivewhl_rm" x_reflect="-1" y_reflect="-1" xoffset="0"/>
  
    <xacro:wheel prefix="drivewhl_lr" x_reflect="-1" y_reflect="1" xoffset="-0.14"/>
    <xacro:wheel prefix="drivewhl_rr" x_reflect="-1" y_reflect="-1" xoffset="-0.14"/>

</robot>